---
title: "VetTweetVolume"
author: "Sam Donnelly"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, options(scipen = 999), message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(dplyr)
library(magrittr)
library(readr)
library(gtrendsR)
library(forecast)
library(tseries)
```

## Read in Twitter Volume
```{r}
vettweetvol <- read.csv("C:/Users/donne/Downloads/VetTweetVol - Sheet2.csv")
vettweetvol$date <- vettweetvol$date %>% #Convert to Date
  as.Date()
vettweetvol <- vettweetvol %>%
  filter(., date != "2020-08-03" & date != "2020-08-04")

# search "d = new Dygraph(" on https://bitinfocharts.com/comparison/tweets-vet.html
```

## Read in Vechain Price
```{r}
vchain <- read.csv("C:/Users/donne/Downloads/vet-usd-max (9).csv")
vchain$date <- as.Date(vchain$snapped_at)
vchain <- vchain %>%
  subset(select = -c(1, 3, 4))
vchain <- vchain %>%
  filter(., date != "2018-12-07" & date != "2018-12-08")
```

## Read in Google Trend by Day
```{r}
dates_ranges=c("2018-12-09 2019-02-08","2019-02-09 2019-05-09","2019-05-10 2019-08-07", "2019-08-08 2019-11-05","2019-11-06 2020-02-03","2020-02-04 2020-05-04","2020-05-05 2020-08-02")

gtrend = data.frame()
for (i in 1:(length(dates_ranges))) { 
  gtrend = rbind(gtrend, (gtrends("vechain", time=dates_ranges[i])$interest_over_time))
}

gtrend <- gtrend %>%
  select(1:2)

write_csv(gtrend, path = "GoogleTrendDay.csv")
```

## Read in adjusted Google Trend by Day
```{r}
gtrend <- read.csv("C:/Users/donne/Downloads/Google Trends Vet - Sheet4.csv")
gtrend$date <- as.Date(gtrend$date) #Convert to class date
names(gtrend)[2] <- "trendvalue"
```

## Create Df
```{r}
df <- left_join(gtrend, vettweetvol, by = "date")
df <- left_join(df, vchain, by = "date")
```

## Forecast: Create Time Series
```{r}
pfc <- ts(df[, 4], start = c(2018, 342), end=c(2020, 214), frequency=365)
vfc <- ts(df[, 3], start = c(2018, 342), end=c(2020, 214), frequency=365)
tfc <- ts(df[, 2], start = c(2018, 342), end=c(2020, 214), frequency=365)

tsdf <- data.frame(pfc, vfc, tfc)

tsmodel <- tslm(formula=pfc ~ vfc, data = tsdf)

fmodel <- forecast(tsmodel, newdata = tsdf, h = 2)

autoplot(cbind(log(pfc), log(vfc), log(tfc)))
```

## KPSS Test 
```{r}
pricemodel <- auto.arima(pfc)
summary(tsmodel)
```

## Interaction Model
```{r}
df$vol_c <- scale(df$vol, scale = FALSE)
df$trendvalue_c <- scale(df$trendvalue, scale = FALSE)

model <- lm(price ~ trendvalue_c*vol_c, df)
summary(model) #R-Square 0.463
```

